### ISSUE TITLE
Missing Anand vs Topalov (2010) Championship

### ISSUE THREAD

**Issue by natrys** [michael1241/wcc_analysis#3]
Hi, nice analysis. A minor detail, you are missing the Anand vs Topalov (2010) match (and analysed_pgn folder contains 2008 match duplicate data with a rename). For completion's sake, maybe you would want to re-run with 2010 included.

**Comment by michael1241** [comment]
Thanks for pointing that out, will fix.

**Comment by michael1241** [comment]
Fixed :+1:
